version: "2"
linters:
  enable:
    - goheader
    - revive
    - unused
  disable-all: true
# all available settings of specific linters
linters-settings:
  goheader:
    values:
      regexp:
        copyright-year: 20[0-9][0-9]
    template-path: code-header-template.txt
  revive:
    enable-all-rules: true
    rules:
    - name: dot-imports
      disabled: true
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new-from-rev: 0ad1b35d4334a8e10856bf9c6d687266430f71d4
