FROM golang:1.17

RUN apt-get update -y
RUN apt-get install wget docker.io apt-transport-https ca-certificates gnupg python -y

RUN wget https://github.com/buildpacks/pack/releases/download/v0.8.1/pack-v0.8.1-linux.tgz
RUN tar -C /usr/local/bin/ -xvf pack-v0.8.1-linux.tgz

RUN wget https://github.com/vmware-tanzu/buildkit-cli-for-kubectl/releases/download/v0.1.0/linux-refs.tags.v0.1.0.tgz
RUN tar -C /usr/local/bin/ -xvf linux-refs.tags.v0.1.0.tgz

RUN wget https://github.com/google/ko/releases/download/v0.8.0/ko_0.8.0_Linux_x86_64.tar.gz
RUN tar -C /usr/local/bin/ -xvf ko_0.8.0_Linux_x86_64.tar.gz

RUN wget https://github.com/bazelbuild/bazel/releases/download/4.2.0/bazel-4.2.0-linux-x86_64 -P /usr/local/bin/
RUN chmod +x /usr/local/bin/bazel-4.2.0-linux-x86_64 && /usr/local/bin/bazel-4.2.0-linux-x86_64 && mv /usr/local/bin/bazel-4.2.0-linux-x86_64 /usr/local/bin/bazel

RUN wget "https://github.com/vmware-tanzu/carvel-kapp/releases/download/v0.48.0/kapp-linux-amd64" -P /usr/local/bin/
RUN chmod +x /usr/local/bin/kapp-linux-amd64
RUN mv /usr/local/bin/kapp-linux-amd64 /usr/local/bin/kapp

RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
RUN curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
RUN apt-get update -y
RUN apt-get install google-cloud-cli -y

RUN git config --global user.email "email@example.com"
RUN git config --global user.name "Some Person"

RUN wget "https://dl.k8s.io/release/$(wget -q https://dl.k8s.io/release/stable.txt -O -)/bin/linux/amd64/kubectl" -P /usr/local/bin/
RUN chmod +x /usr/local/bin/kubectl

