FROM golang:1.19

RUN apt-get update -y
RUN apt-get install docker.io apt-transport-https ca-certificates gnupg python -y

RUN mkdir -p ~/.docker/cli-plugins/
RUN curl -sLo ~/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/v0.8.2/buildx-v0.8.2.linux-amd64
RUN chmod +x ~/.docker/cli-plugins/docker-buildx

RUN curl -sL https://github.com/buildpacks/pack/releases/download/v0.8.1/pack-v0.8.1-linux.tgz | tar -C /usr/local/bin -xz

RUN curl -sL https://github.com/vmware-tanzu/buildkit-cli-for-kubectl/releases/download/v0.1.0/linux-refs.tags.v0.1.0.tgz | tar -C /usr/local/bin -xz

RUN curl -sL https://github.com/google/ko/releases/download/v0.8.0/ko_0.8.0_Linux_x86_64.tar.gz | tar -C /usr/local/bin -xz

RUN curl -sLo /usr/local/bin/bazel https://github.com/bazelbuild/bazel/releases/download/4.2.0/bazel-4.2.0-linux-x86_64
RUN chmod +x /usr/local/bin/bazel

RUN curl -sLo /usr/local/bin/kapp https://github.com/carvel-dev/kapp/releases/download/v0.48.0/kapp-linux-amd64
RUN chmod +x /usr/local/bin/kapp

RUN curl -sLo /usr/local/bin/ytt https://github.com/carvel-dev/ytt/releases/download/v0.41.1/ytt-linux-amd64
RUN chmod +x /usr/local/bin/ytt

RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
RUN curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor > /usr/share/keyrings/cloud.google.gpg
RUN apt-get update -y
RUN apt-get install google-cloud-cli -y

RUN git config --global user.email "email@example.com"
RUN git config --global user.name "Some Person"

RUN curl -sLo /usr/local/bin/kubectl "https://dl.k8s.io/release/$(curl -sL https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
RUN chmod +x /usr/local/bin/kubectl

COPY ./ /go/src/kbld/
