apiVersion: apps/v1
kind: Deployment
metadata:
  name: kbld-simple-app-build-local-bazel
spec:
  selector:
    matchLabels:
      app: kbld-simple-app-build-local-bazel
  template:
    metadata:
      labels:
        app: kbld-simple-app-build-local-bazel
    spec:
      containers:
      - name: my-app
        image: simple-app
---
apiVersion: kbld.k14s.io/v1alpha1
kind: Config
sources:
- image: simple-app
  path: test/e2e/assets/simple-app
  bazel:
    build:
      label: :simple-app
